services:
  - type: web
    name: perceptionX
    env: node
    plan: free
    buildCommand: |
      npm install
      pip install -r requirements.txt
    startCommand: node app.js
    envVars:
      - key: PORT
        value: "3000"
